env:
  browser: true
  es6: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "prettier"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
overrides:
  [{ "files": ["**/*.test.js", "**/*.test.jsx"], "env": { "jest": true } }]
rules: {}
